In [1]:
!pip install pydub

import os
import pandas as pd
import numpy as np 
import seaborn as sns
from tqdm import tqdm

from pydub import AudioSegment
from IPython.display import Audio

import librosa
import librosa.display
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pydub
  Downloading pydub-0.25.1-py2.py3-none-any.whl (32 kB)
Installing collected packages: pydub
Successfully installed pydub-0.25.1

In [2]:
# creating the dataframe which has path to wav file and it's label

label = []
path = []

root = '/content/drive/MyDrive/Bird/dataset/whole_dataset/train_val/train_data'
for species in os.listdir(root):
    species_folder = root + '/' + species
    for audio in os.listdir(species_folder):
        audio_path = species_folder + '/' + audio
        path.append(audio_path)
        label.append(species)
        
df_train = pd.DataFrame({'path': path,
                         'class_name': label})
print(df_train.shape)
df_train.sample(5)

(974, 2)

                                                  path class_name
865  /content/drive/MyDrive/Bird/dataset/whole_data...    lapwing
891  /content/drive/MyDrive/Bird/dataset/whole_data...        owl
162  /content/drive/MyDrive/Bird/dataset/whole_data...       duck
575  /content/drive/MyDrive/Bird/dataset/whole_data...    bluejay
208  /content/drive/MyDrive/Bird/dataset/whole_data...       crow

In [3]:
# adding numerical class labels to each audio files

cls_label = {'Asiankoel' : 0, 'bluejay': 1, 'crow': 2, 'duck': 3, 'goaway': 4, 'lapwing': 5, 'owl': 6,
       'peafowl' : 7, 'sparrow':8, 'woodpeewe':9}

def name_to_label(x):
  cls_name = x['class_name']
  return cls_label[cls_name]

df_train['class_label'] = df_train.apply(name_to_label, axis=1)
df_train.sample(5)

                                                  path class_name  class_label
689  /content/drive/MyDrive/Bird/dataset/whole_data...  woodpeewe            9
286  /content/drive/MyDrive/Bird/dataset/whole_data...       crow            2
729  /content/drive/MyDrive/Bird/dataset/whole_data...  woodpeewe            9
449  /content/drive/MyDrive/Bird/dataset/whole_data...    sparrow            8
408  /content/drive/MyDrive/Bird/dataset/whole_data...    sparrow            8

In [4]:
# creating the dataframe which has path to wav file and it's label

label = []
path = []

root = '/content/drive/MyDrive/Bird/dataset/whole_dataset/train_val/validation_data'
for species in os.listdir(root):
    species_folder = root + '/' + species
    for audio in os.listdir(species_folder):
        audio_path = species_folder + '/' + audio
        path.append(audio_path)
        label.append(species)
        
df_test = pd.DataFrame({'path': path,
                         'class_name': label})
print(df_test.shape)
df_test.sample(5)

(104, 2)

                                                 path class_name
72  /content/drive/MyDrive/Bird/dataset/whole_data...    lapwing
96  /content/drive/MyDrive/Bird/dataset/whole_data...       crow
6   /content/drive/MyDrive/Bird/dataset/whole_data...        owl
28  /content/drive/MyDrive/Bird/dataset/whole_data...     goaway
10  /content/drive/MyDrive/Bird/dataset/whole_data...  woodpeewe

In [5]:
# adding numerical class labels to each audio files

cls_label = {'Asiankoel' : 0, 'bluejay': 1, 'crow': 2, 'duck': 3, 'goaway': 4, 'lapwing': 5, 'owl': 6,
       'peafowl' : 7, 'sparrow':8, 'woodpeewe':9}

def name_to_label(x):
  cls_name = x['class_name']
  return cls_label[cls_name]

df_test['class_label'] = df_test.apply(name_to_label, axis=1)
df_test.sample(5)

                                                 path class_name  class_label
16  /content/drive/MyDrive/Bird/dataset/whole_data...  woodpeewe            9
76  /content/drive/MyDrive/Bird/dataset/whole_data...    lapwing            5
54  /content/drive/MyDrive/Bird/dataset/whole_data...  Asiankoel            0
61  /content/drive/MyDrive/Bird/dataset/whole_data...  Asiankoel            0
91  /content/drive/MyDrive/Bird/dataset/whole_data...    peafowl            7

In [6]:
!pip install pydub

import os
import pandas as pd
import numpy as np 
import seaborn as sns
from tqdm import tqdm

from pydub import AudioSegment
from IPython.display import Audio

import librosa
import librosa.display
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pydub in /usr/local/lib/python3.8/dist-packages (0.25.1)

In [7]:
# creating the dataframe which has path to wav file and it's label

label = []
path = []

root = '/content/drive/MyDrive/Bird/dataset/whole_dataset/train_val/train_data'
for species in os.listdir(root):
    species_folder = root + '/' + species
    for audio in os.listdir(species_folder):
        audio_path = species_folder + '/' + audio
        path.append(audio_path)
        label.append(species)
        
df_train = pd.DataFrame({'path': path,
                         'class_name': label})
print(df_train.shape)
df_train.sample(5)

(974, 2)

                                                  path class_name
431  /content/drive/MyDrive/Bird/dataset/whole_data...    sparrow
937  /content/drive/MyDrive/Bird/dataset/whole_data...        owl
37   /content/drive/MyDrive/Bird/dataset/whole_data...    peafowl
101  /content/drive/MyDrive/Bird/dataset/whole_data...       duck
512  /content/drive/MyDrive/Bird/dataset/whole_data...    bluejay

In [8]:
# adding numerical class labels to each audio files

cls_label = {'Asiankoel' : 0, 'bluejay': 1, 'crow': 2, 'duck': 3, 'goaway': 4, 'lapwing': 5, 'owl': 6,
       'peafowl' : 7, 'sparrow':8, 'woodpeewe':9}

def name_to_label(x):
  cls_name = x['class_name']
  return cls_label[cls_name]

df_train['class_label'] = df_train.apply(name_to_label, axis=1)
df_train.sample(5)

                                                  path class_name  class_label
74   /content/drive/MyDrive/Bird/dataset/whole_data...    peafowl            7
479  /content/drive/MyDrive/Bird/dataset/whole_data...    sparrow            8
214  /content/drive/MyDrive/Bird/dataset/whole_data...       crow            2
527  /content/drive/MyDrive/Bird/dataset/whole_data...    bluejay            1
501  /content/drive/MyDrive/Bird/dataset/whole_data...    bluejay            1

In [9]:
# creating the dataframe which has path to wav file and it's label

label = []
path = []

root = '/content/drive/MyDrive/Bird/dataset/whole_dataset/train_val/validation_data'
for species in os.listdir(root):
    species_folder = root + '/' + species
    for audio in os.listdir(species_folder):
        audio_path = species_folder + '/' + audio
        path.append(audio_path)
        label.append(species)
        
df_test = pd.DataFrame({'path': path,
                         'class_name': label})
print(df_test.shape)
df_test.sample(5)

(104, 2)

                                                 path class_name
61  /content/drive/MyDrive/Bird/dataset/whole_data...  Asiankoel
13  /content/drive/MyDrive/Bird/dataset/whole_data...  woodpeewe
41  /content/drive/MyDrive/Bird/dataset/whole_data...       duck
14  /content/drive/MyDrive/Bird/dataset/whole_data...  woodpeewe
70  /content/drive/MyDrive/Bird/dataset/whole_data...    bluejay

In [10]:
# adding numerical class labels to each audio files

cls_label = {'Asiankoel' : 0, 'bluejay': 1, 'crow': 2, 'duck': 3, 'goaway': 4, 'lapwing': 5, 'owl': 6,
       'peafowl' : 7, 'sparrow':8, 'woodpeewe':9}

def name_to_label(x):
  cls_name = x['class_name']
  return cls_label[cls_name]

df_test['class_label'] = df_test.apply(name_to_label, axis=1)
df_test.sample(5)

                                                 path class_name  class_label
61  /content/drive/MyDrive/Bird/dataset/whole_data...  Asiankoel            0
80  /content/drive/MyDrive/Bird/dataset/whole_data...    lapwing            5
91  /content/drive/MyDrive/Bird/dataset/whole_data...    peafowl            7
96  /content/drive/MyDrive/Bird/dataset/whole_data...       crow            2
59  /content/drive/MyDrive/Bird/dataset/whole_data...  Asiankoel            0

In [11]:
#train set
X_train = df_train['path']
y_train = df_train['class_label']

#test set
X_test = df_test['path']
y_test = df_test['class_label']

X_train.shape, y_train.shape, X_test.shape, y_test.shape

((974,), (974,), (104,), (104,))

In [12]:
#getting mfcc features for all the data points in test and train

def get_spec(path):
    y, sr = librosa.load(path)
    S = librosa.feature.melspectrogram(y=y, sr=sr)
    return S

In [13]:
# train data
temp = []
label = []
for i in tqdm(range(len(X_train))):
  audio_path = X_train.iloc[i]
  mfcc = get_spec(audio_path)
  mfcc = np.resize(mfcc, (65, 40,))
  temp.append(mfcc)
  label.append(y_train.iloc[i])

X_train_processed = np.asarray(temp)
y_train = np.asarray(label)

X_train_processed.shape, y_train.shape

100%|██████████| 974/974 [07:03<00:00,  2.30it/s]

((974, 65, 40), (974,))

In [14]:
#test data
temp = []
label = []

for i in tqdm(range(len(X_test))):
  audio_path = X_test.iloc[i]
  mfcc = get_spec(audio_path)
  mfcc = np.resize(mfcc, (65, 40))
  temp.append(mfcc)
  label.append(y_test.iloc[i])

X_test_processed = np.asarray(temp)
y_test = np.asarray(label)

X_test_processed.shape, y_test.shape

100%|██████████| 104/104 [00:46<00:00,  2.26it/s]

((104, 65, 40), (104,))

#### Modelling

In [15]:
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.models import Model

tf.keras.backend.clear_session()

In [16]:
#Create model

#input
input = layers.Input(shape=(65,40), name='input_layer')

#cnn
x = layers.Conv1D(64, (3,), activation='relu')(input)
 
#lstm
x = layers.LSTM(128, return_sequences = False)(x)

#dense
x = layers.Dense(64,'relu')(x)

#output
output = layers.Dense(10, 'sigmoid', name='output_layer')(x)

model = Model(inputs=input, outputs=output)
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_layer (InputLayer)    [(None, 65, 40)]          0

 conv1d (Conv1D)             (None, 63, 64)            7744

 lstm (LSTM)                 (None, 128)               98816

 dense (Dense)               (None, 64)                8256

 output_layer (Dense)        (None, 10)                650

=================================================================
Total params: 115,466
Trainable params: 115,466
Non-trainable params: 0
_________________________________________________________________

In [17]:
#compile
ls = tf.keras.losses.SparseCategoricalCrossentropy()
adam = tf.keras.optimizers.Adam(learning_rate = 0.001)
model.compile(adam, ls, metrics='accuracy')

#fitting
history = model.fit(X_train_processed, y_train, 
                    validation_data = (X_test_processed, y_test),
                    epochs = 20)

Epoch 1/20
31/31 [==============================] - 4s 79ms/step - loss: 2.0863 - accuracy: 0.2669 - val_loss: 1.9730 - val_accuracy: 0.2692
Epoch 2/20
31/31 [==============================] - 2s 66ms/step - loss: 1.7719 - accuracy: 0.3368 - val_loss: 1.6369 - val_accuracy: 0.3654
Epoch 3/20
31/31 [==============================] - 2s 65ms/step - loss: 1.5462 - accuracy: 0.4158 - val_loss: 1.5865 - val_accuracy: 0.3365
Epoch 4/20
31/31 [==============================] - 2s 64ms/step - loss: 1.3780 - accuracy: 0.4856 - val_loss: 1.5469 - val_accuracy: 0.4038
Epoch 5/20
31/31 [==============================] - 2s 65ms/step - loss: 1.3098 - accuracy: 0.4979 - val_loss: 1.2476 - val_accuracy: 0.5577
Epoch 6/20
31/31 [==============================] - 3s 100ms/step - loss: 1.1716 - accuracy: 0.5575 - val_loss: 1.4120 - val_accuracy: 0.4904
Epoch 7/20
31/31 [==============================] - 2s 64ms/step - loss: 1.1719 - accuracy: 0.5575 - val_loss: 1.2573 - val_accuracy: 0.5481
Epoch 8/20
31/31 [==============================] - 2s 65ms/step - loss: 1.0416 - accuracy: 0.5924 - val_loss: 1.1130 - val_accuracy: 0.6250
Epoch 9/20
31/31 [==============================] - 2s 64ms/step - loss: 1.0418 - accuracy: 0.6078 - val_loss: 1.1324 - val_accuracy: 0.6346
Epoch 10/20
31/31 [==============================] - 2s 64ms/step - loss: 0.9904 - accuracy: 0.6335 - val_loss: 1.1067 - val_accuracy: 0.5769
Epoch 11/20
31/31 [==============================] - 2s 73ms/step - loss: 0.9624 - accuracy: 0.6253 - val_loss: 1.0744 - val_accuracy: 0.7019
Epoch 12/20
31/31 [==============================] - 2s 80ms/step - loss: 0.9323 - accuracy: 0.6591 - val_loss: 1.0065 - val_accuracy: 0.6058
Epoch 13/20
31/31 [==============================] - 2s 64ms/step - loss: 0.8681 - accuracy: 0.6715 - val_loss: 1.0909 - val_accuracy: 0.6250
Epoch 14/20
31/31 [==============================] - 2s 65ms/step - loss: 0.8383 - accuracy: 0.6858 - val_loss: 1.0040 - val_accuracy: 0.6635
Epoch 15/20
31/31 [==============================] - 2s 65ms/step - loss: 0.8239 - accuracy: 0.6920 - val_loss: 1.1524 - val_accuracy: 0.6154
Epoch 16/20
31/31 [==============================] - 2s 64ms/step - loss: 0.8369 - accuracy: 0.6869 - val_loss: 1.0888 - val_accuracy: 0.6442
Epoch 17/20
31/31 [==============================] - 2s 65ms/step - loss: 0.7898 - accuracy: 0.7012 - val_loss: 1.0048 - val_accuracy: 0.6923
Epoch 18/20
31/31 [==============================] - 2s 65ms/step - loss: 0.7110 - accuracy: 0.7526 - val_loss: 1.0649 - val_accuracy: 0.6731
Epoch 19/20
31/31 [==============================] - 2s 65ms/step - loss: 0.7482 - accuracy: 0.7413 - val_loss: 1.2641 - val_accuracy: 0.6058
Epoch 20/20
31/31 [==============================] - 2s 65ms/step - loss: 0.7867 - accuracy: 0.7146 - val_loss: 1.0176 - val_accuracy: 0.7115

#### Predictions

In [18]:
!pip install pydub

import os 
from multiprocessing import Pool

import pandas as pd
import numpy as np

from sklearn.metrics import f1_score
from scipy.sparse import lil_matrix

import tensorflow as tf 
from tqdm import tqdm

import librosa
from pydub import AudioSegment
from pydub.utils import make_chunks
from IPython.display import Audio

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pydub in /usr/local/lib/python3.8/dist-packages (0.25.1)

In [19]:
#assigning numerical class labels to each bird species

cls_label = {'Asiankoel' : 0, 'bluejay': 1, 'crow': 2, 'duck': 3, 'goaway': 4, 'lapwing': 5, 'owl': 6,
             'peafowl' : 7, 'sparrow':8, 'woodpeewe':9}

########################################################

def get_class_labels(r):
  x = r['class_name']
  label_names = x.split('_')

  label_nums=[]
  for l in label_names:
    indx = cls_label[l]
    label_nums.append(indx)

  return label_nums

In [20]:
# creating the dataframe which has path to wav file and it's label
# 2 species test dataset
label = []
path = []

root = '/content/drive/MyDrive/Bird/dataset/whole_dataset/mix_2'
for species in os.listdir(root):
    species_folder = root + '/' + species
    for audio in os.listdir(species_folder):
        audio_path = species_folder + '/' + audio
        path.append(audio_path)
        label.append(species)
        
df_mix_2 = pd.DataFrame({'path': path,
                         'class_name': label})

df_mix_2['class_label'] = df_mix_2.apply(get_class_labels, axis=1)

print(df_mix_2.shape)
df_mix_2.sample(5)

(334, 3)

,path,class_name,class_label
50,/content/drive/MyDrive/Bird/dataset/whole_data...,owl_goaway,"[6, 4]"
200,/content/drive/MyDrive/Bird/dataset/whole_data...,woodpeewe_duck,"[9, 3]"
241,/content/drive/MyDrive/Bird/dataset/whole_data...,woodpeewe_lapwing,"[9, 5]"
72,/content/drive/MyDrive/Bird/dataset/whole_data...,sparrow_bluejay,"[8, 1]"
154,/content/drive/MyDrive/Bird/dataset/whole_data...,lapwing_owl,"[5, 6]"

In [21]:
# 3 species test dataset 
label = []
path = []

root = '/content/drive/MyDrive/Bird/dataset/whole_dataset/mix_3'
for species in os.listdir(root):
    species_folder = root + '/' + species
    for audio in os.listdir(species_folder):
        audio_path = species_folder + '/' + audio
        path.append(audio_path)
        label.append(species)
        
df_mix_3 = pd.DataFrame({'path': path,
                         'class_name': label})

df_mix_3['class_label'] = df_mix_3.apply(get_class_labels, axis=1)

print(df_mix_3.shape)
df_mix_3.sample(5)

(100, 3)

,path,class_name,class_label
85,/content/drive/MyDrive/Bird/dataset/whole_data...,bluejay_lapwing_crow,"[1, 5, 2]"
11,/content/drive/MyDrive/Bird/dataset/whole_data...,crow_sparrow_goaway,"[2, 8, 4]"
13,/content/drive/MyDrive/Bird/dataset/whole_data...,bluejay_woodpeewe_crow,"[1, 9, 2]"
76,/content/drive/MyDrive/Bird/dataset/whole_data...,bluejay_sparrow_goaway,"[1, 8, 4]"
75,/content/drive/MyDrive/Bird/dataset/whole_data...,crow_owl_goaway,"[2, 6, 4]"

In [22]:
# whole test data i.e mixture of both 2 and 3 species audio files
df = pd.concat([df_mix_2, df_mix_3], ignore_index = True)
df.sample(5)

,path,class_name,class_label
14,/content/drive/MyDrive/Bird/dataset/whole_data...,bluejay_goaway,"[1, 4]"
339,/content/drive/MyDrive/Bird/dataset/whole_data...,duck_sparrow_goaway,"[3, 8, 4]"
343,/content/drive/MyDrive/Bird/dataset/whole_data...,duck_sparrow_Asiankoel,"[3, 8, 0]"
186,/content/drive/MyDrive/Bird/dataset/whole_data...,woodpeewe_bluejay,"[9, 1]"
237,/content/drive/MyDrive/Bird/dataset/whole_data...,peafowl_sparrow,"[7, 8]"

In [23]:
# ref: https://www.kaggle.com/code/arailly/multi-label-f-beta-score/notebook

# metrics function

def label_to_sm(labels, n_classes):
    sm = lil_matrix((len(labels), n_classes))
    for i, label in enumerate(labels):
        sm[i, label] = 1  #eg: sm[0, [2,3]] = 1
    return sm

###############################################

def get_f1_score(y_true, y_pred):
  y_true_sm = label_to_sm(labels=y_true, n_classes=10)
  y_pred_sm = label_to_sm(labels=y_pred, n_classes=10)
  metric = f1_score(y_true=y_true_sm, y_pred=y_pred_sm, average='weighted')
  return metric

#################################################

def get_sm(y_true, y_pred):
  y_true_sm = label_to_sm(labels=y_true, n_classes=10)
  y_pred_sm = label_to_sm(labels=y_pred, n_classes=10)
  return y_true_sm, y_pred_sm

In [24]:
def get_split(path):
  myaudio = AudioSegment.from_file(path , "wav") 
  chunk_length_ms = 1500 # pydub calculates in millisec
  chunks = make_chunks(myaudio, chunk_length_ms) #Make chunks of one sec

  #Export all of the individual chunks as wav files
  paths =[]

  for i, chunk in enumerate(chunks):
      chunk_name = "chunk{0}.wav".format(i)
      paths.append(chunk_name)
      chunk.export(chunk_name, format="wav")

  return paths

##################################################

def get_spec(path):
    y, sr = librosa.load(path)
    S = librosa.feature.melspectrogram(y=y, sr=sr)
    return np.resize(S, (65, 40))

##################################################

def get_xqs(paths):
  xqs = []
  for i in range(6): #only using first 6 chunks
    t = get_spec(paths[i])
    xqs.append(t)
  return xqs

In [25]:
def get_probs(model, xqs):
  probs = []
  for xq in xqs:
    xq = xq.reshape((1,65,40))
    p = model.predict(xq, verbose = 0)
    probs.append(p)
  return np.array(probs)

def predict(model, xqs, num_species):
  probs = get_probs(model, xqs)
  # aggregrate
  # s = np.sum(probs, axis = 0)
  s = np.max(probs, axis = 0)
  if num_species == 2: 
    n = 2
  else:
    n = 3
  labels = np.argsort(s[0])[::-1][:n]
  return list(labels)

In [26]:
def test(model, df, num_species):
  y_true = list(df['class_label'])
  y_pred = []
  for i in tqdm(range(len(df))):
    path = df['path'][i]
    chunk_paths = get_split(path)
    xqs = get_xqs(chunk_paths)
    label = predict(model, xqs, num_species)
    y_pred.append(label)
  return y_true, y_pred

#########################################################

def evaluate(model, df_mix_2, df_mix_3):
  y_true_2, y_pred_2 = test(model, df_mix_2, 2)
  y_true_3, y_pred_3 = test(model, df_mix_3, 3)
  
  y_true = y_true_2 + y_true_3
  y_pred = y_pred_2 + y_pred_3
  score = get_f1_score(y_true, y_pred)
  
  return y_true, y_pred, score

In [27]:
y_true, y_pred, score = evaluate(model, df_mix_2, df_mix_3)
score

100%|██████████| 334/334 [05:10<00:00,  1.08it/s]
100%|██████████| 100/100 [01:28<00:00,  1.13it/s]

0.4672354597472585

In [28]:
from sklearn.metrics import classification_report

y_true, y_pred = get_sm(y_true, y_pred)
print(classification_report(y_true, y_pred))

              precision    recall  f1-score   support

           0       0.31      0.77      0.44        69
           1       0.12      0.03      0.05       101
           2       0.61      0.62      0.62       100
           3       0.46      0.66      0.54        88
           4       0.59      0.94      0.72       145
           5       0.69      0.44      0.54       136
           6       0.24      0.22      0.23        55
           7       0.66      0.90      0.77        63
           8       0.32      0.10      0.15       119
           9       0.78      0.42      0.55        92

   micro avg       0.51      0.51      0.51       968
   macro avg       0.48      0.51      0.46       968
weighted avg       0.50      0.51      0.47       968
 samples avg       0.52      0.52      0.52       968