In [1]:
!pip install pydub

import os
import pandas as pd
import numpy as np 
import seaborn as sns
from tqdm import tqdm

from pydub import AudioSegment
from IPython.display import Audio

import librosa
import librosa.display
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pydub
  Downloading pydub-0.25.1-py2.py3-none-any.whl (32 kB)
Installing collected packages: pydub
Successfully installed pydub-0.25.1

In [2]:
# creating the dataframe which has path to wav file and it's label

label = []
path = []

root = '/content/drive/MyDrive/Bird/dataset/whole_dataset/train_val/train_data'
for species in os.listdir(root):
    species_folder = root + '/' + species
    for audio in os.listdir(species_folder):
        audio_path = species_folder + '/' + audio
        path.append(audio_path)
        label.append(species)
        
df_train = pd.DataFrame({'path': path,
                         'class_name': label})
print(df_train.shape)
df_train.sample(5)

(974, 2)

                                                  path class_name
635  /content/drive/MyDrive/Bird/dataset/whole_data...     goaway
832  /content/drive/MyDrive/Bird/dataset/whole_data...    lapwing
631  /content/drive/MyDrive/Bird/dataset/whole_data...     goaway
937  /content/drive/MyDrive/Bird/dataset/whole_data...        owl
943  /content/drive/MyDrive/Bird/dataset/whole_data...        owl

In [3]:
# adding numerical class labels to each audio files

cls_label = {'Asiankoel' : 0, 'bluejay': 1, 'crow': 2, 'duck': 3, 'goaway': 4, 'lapwing': 5, 'owl': 6,
       'peafowl' : 7, 'sparrow':8, 'woodpeewe':9}

def name_to_label(x):
  cls_name = x['class_name']
  return cls_label[cls_name]

df_train['class_label'] = df_train.apply(name_to_label, axis=1)
df_train.sample(5)

                                                  path class_name  class_label
427  /content/drive/MyDrive/Bird/dataset/whole_data...    sparrow            8
956  /content/drive/MyDrive/Bird/dataset/whole_data...        owl            6
54   /content/drive/MyDrive/Bird/dataset/whole_data...    peafowl            7
639  /content/drive/MyDrive/Bird/dataset/whole_data...     goaway            4
934  /content/drive/MyDrive/Bird/dataset/whole_data...        owl            6

In [4]:
# creating the dataframe which has path to wav file and it's label

label = []
path = []

root = '/content/drive/MyDrive/Bird/dataset/whole_dataset/train_val/validation_data'
for species in os.listdir(root):
    species_folder = root + '/' + species
    for audio in os.listdir(species_folder):
        audio_path = species_folder + '/' + audio
        path.append(audio_path)
        label.append(species)
        
df_test = pd.DataFrame({'path': path,
                         'class_name': label})
print(df_test.shape)
df_test.sample(5)

(104, 2)

                                                 path class_name
87  /content/drive/MyDrive/Bird/dataset/whole_data...    peafowl
25  /content/drive/MyDrive/Bird/dataset/whole_data...     goaway
41  /content/drive/MyDrive/Bird/dataset/whole_data...       duck
31  /content/drive/MyDrive/Bird/dataset/whole_data...    sparrow
33  /content/drive/MyDrive/Bird/dataset/whole_data...    sparrow

In [5]:
# adding numerical class labels to each audio files

cls_label = {'Asiankoel' : 0, 'bluejay': 1, 'crow': 2, 'duck': 3, 'goaway': 4, 'lapwing': 5, 'owl': 6,
       'peafowl' : 7, 'sparrow':8, 'woodpeewe':9}

def name_to_label(x):
  cls_name = x['class_name']
  return cls_label[cls_name]

df_test['class_label'] = df_test.apply(name_to_label, axis=1)
df_test.sample(5)

                                                  path class_name  class_label
18   /content/drive/MyDrive/Bird/dataset/whole_data...  woodpeewe            9
24   /content/drive/MyDrive/Bird/dataset/whole_data...     goaway            4
48   /content/drive/MyDrive/Bird/dataset/whole_data...       duck            3
101  /content/drive/MyDrive/Bird/dataset/whole_data...       crow            2
43   /content/drive/MyDrive/Bird/dataset/whole_data...       duck            3

In [6]:
!pip install pydub

import os
import pandas as pd
import numpy as np 
import seaborn as sns
from tqdm import tqdm

from pydub import AudioSegment
from IPython.display import Audio

import librosa
import librosa.display
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pydub in /usr/local/lib/python3.8/dist-packages (0.25.1)

In [7]:
# creating the dataframe which has path to wav file and it's label

label = []
path = []

root = '/content/drive/MyDrive/Bird/dataset/whole_dataset/train_val/train_data'
for species in os.listdir(root):
    species_folder = root + '/' + species
    for audio in os.listdir(species_folder):
        audio_path = species_folder + '/' + audio
        path.append(audio_path)
        label.append(species)
        
df_train = pd.DataFrame({'path': path,
                         'class_name': label})
print(df_train.shape)
df_train.sample(5)

(974, 2)

                                                  path class_name
839  /content/drive/MyDrive/Bird/dataset/whole_data...    lapwing
937  /content/drive/MyDrive/Bird/dataset/whole_data...        owl
547  /content/drive/MyDrive/Bird/dataset/whole_data...    bluejay
831  /content/drive/MyDrive/Bird/dataset/whole_data...    lapwing
291  /content/drive/MyDrive/Bird/dataset/whole_data...  Asiankoel

In [8]:
# adding numerical class labels to each audio files

cls_label = {'Asiankoel' : 0, 'bluejay': 1, 'crow': 2, 'duck': 3, 'goaway': 4, 'lapwing': 5, 'owl': 6,
       'peafowl' : 7, 'sparrow':8, 'woodpeewe':9}

def name_to_label(x):
  cls_name = x['class_name']
  return cls_label[cls_name]

df_train['class_label'] = df_train.apply(name_to_label, axis=1)
df_train.sample(5)

                                                  path class_name  class_label
226  /content/drive/MyDrive/Bird/dataset/whole_data...       crow            2
869  /content/drive/MyDrive/Bird/dataset/whole_data...    lapwing            5
76   /content/drive/MyDrive/Bird/dataset/whole_data...    peafowl            7
813  /content/drive/MyDrive/Bird/dataset/whole_data...    lapwing            5
332  /content/drive/MyDrive/Bird/dataset/whole_data...  Asiankoel            0

In [9]:
# creating the dataframe which has path to wav file and it's label

label = []
path = []

root = '/content/drive/MyDrive/Bird/dataset/whole_dataset/train_val/validation_data'
for species in os.listdir(root):
    species_folder = root + '/' + species
    for audio in os.listdir(species_folder):
        audio_path = species_folder + '/' + audio
        path.append(audio_path)
        label.append(species)
        
df_test = pd.DataFrame({'path': path,
                         'class_name': label})
print(df_test.shape)
df_test.sample(5)

(104, 2)

                                                  path class_name
2    /content/drive/MyDrive/Bird/dataset/whole_data...        owl
103  /content/drive/MyDrive/Bird/dataset/whole_data...       crow
90   /content/drive/MyDrive/Bird/dataset/whole_data...    peafowl
60   /content/drive/MyDrive/Bird/dataset/whole_data...  Asiankoel
25   /content/drive/MyDrive/Bird/dataset/whole_data...     goaway

In [10]:
# adding numerical class labels to each audio files

cls_label = {'Asiankoel' : 0, 'bluejay': 1, 'crow': 2, 'duck': 3, 'goaway': 4, 'lapwing': 5, 'owl': 6,
       'peafowl' : 7, 'sparrow':8, 'woodpeewe':9}

def name_to_label(x):
  cls_name = x['class_name']
  return cls_label[cls_name]

df_test['class_label'] = df_test.apply(name_to_label, axis=1)
df_test.sample(5)

                                                 path class_name  class_label
92  /content/drive/MyDrive/Bird/dataset/whole_data...    peafowl            7
2   /content/drive/MyDrive/Bird/dataset/whole_data...        owl            6
79  /content/drive/MyDrive/Bird/dataset/whole_data...    lapwing            5
45  /content/drive/MyDrive/Bird/dataset/whole_data...       duck            3
64  /content/drive/MyDrive/Bird/dataset/whole_data...    bluejay            1

In [11]:
#train set
X_train = df_train['path']
y_train = df_train['class_label']

#test set
X_test = df_test['path']
y_test = df_test['class_label']

X_train.shape, y_train.shape, X_test.shape, y_test.shape

((974,), (974,), (104,), (104,))

In [12]:
#getting mfcc features for all the data points in test and train

def get_mfcc(path):
    y, sr = librosa.load(path)
    S = librosa.feature.melspectrogram(y=y, sr=sr)
    mfccs = librosa.feature.mfcc(S=librosa.power_to_db(S), n_mfcc=40)
    return mfccs.T

In [13]:
# train data
temp = []
label = []
for i in tqdm(range(len(X_train))):
  audio_path = X_train.iloc[i]
  mfcc = get_mfcc(audio_path)
  mfcc = np.resize(mfcc, (65, 40,))
  temp.append(mfcc)
  label.append(y_train.iloc[i])

X_train_processed = np.asarray(temp)
y_train = np.asarray(label)

X_train_processed.shape, y_train.shape

100%|██████████| 974/974 [12:47<00:00,  1.27it/s]

((974, 65, 40), (974,))

In [14]:
#test data
temp = []
label = []

for i in tqdm(range(len(X_test))):
  audio_path = X_test.iloc[i]
  mfcc = get_mfcc(audio_path)
  mfcc = np.resize(mfcc, (65, 40))
  temp.append(mfcc)
  label.append(y_test.iloc[i])

X_test_processed = np.asarray(temp)
y_test = np.asarray(label)

X_test_processed.shape, y_test.shape

100%|██████████| 104/104 [01:24<00:00,  1.23it/s]

((104, 65, 40), (104,))

#### Modelling

In [15]:
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.models import Model

tf.keras.backend.clear_session()

In [16]:
#Create model

#input
input = layers.Input(shape=(65,40), name='input_layer')

#cnn
x = layers.Conv1D(64, (3,), activation='relu')(input)
 
#lstm
x = layers.LSTM(128, return_sequences = False)(x)

#dense
x = layers.Dense(64,'relu')(x)

#output
output = layers.Dense(10, 'sigmoid', name='output_layer')(x)

model = Model(inputs=input, outputs=output)
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_layer (InputLayer)    [(None, 65, 40)]          0

 conv1d (Conv1D)             (None, 63, 64)            7744

 lstm (LSTM)                 (None, 128)               98816

 dense (Dense)               (None, 64)                8256

 output_layer (Dense)        (None, 10)                650

=================================================================
Total params: 115,466
Trainable params: 115,466
Non-trainable params: 0
_________________________________________________________________

In [28]:
#compile
ls = tf.keras.losses.SparseCategoricalCrossentropy()
adam = tf.keras.optimizers.Adam(learning_rate = 0.001)
model.compile(adam, ls, metrics='accuracy')

#fitting
history = model.fit(X_train_processed, y_train, 
                    validation_data = (X_test_processed, y_test),
                    epochs = 20)

Epoch 1/20
31/31 [==============================] - 6s 121ms/step - loss: 0.0621 - accuracy: 0.9867 - val_loss: 0.1695 - val_accuracy: 0.9808
Epoch 2/20
31/31 [==============================] - 3s 104ms/step - loss: 0.0395 - accuracy: 0.9949 - val_loss: 0.1931 - val_accuracy: 0.9423
Epoch 3/20
31/31 [==============================] - 3s 101ms/step - loss: 0.0317 - accuracy: 0.9949 - val_loss: 0.1515 - val_accuracy: 0.9615
Epoch 4/20
31/31 [==============================] - 3s 102ms/step - loss: 0.0238 - accuracy: 0.9979 - val_loss: 0.1312 - val_accuracy: 0.9712
Epoch 5/20
31/31 [==============================] - 3s 100ms/step - loss: 0.0121 - accuracy: 0.9990 - val_loss: 0.1540 - val_accuracy: 0.9615
Epoch 6/20
31/31 [==============================] - 3s 102ms/step - loss: 0.0154 - accuracy: 0.9979 - val_loss: 0.1456 - val_accuracy: 0.9712
Epoch 7/20
31/31 [==============================] - 3s 100ms/step - loss: 0.0324 - accuracy: 0.9959 - val_loss: 0.1556 - val_accuracy: 0.9712
Epoch 8/20
31/31 [==============================] - 3s 101ms/step - loss: 0.0121 - accuracy: 0.9990 - val_loss: 0.1197 - val_accuracy: 0.9712
Epoch 9/20
31/31 [==============================] - 3s 102ms/step - loss: 0.0086 - accuracy: 1.0000 - val_loss: 0.1488 - val_accuracy: 0.9712
Epoch 10/20
31/31 [==============================] - 3s 102ms/step - loss: 0.0065 - accuracy: 1.0000 - val_loss: 0.1303 - val_accuracy: 0.9808
Epoch 11/20
31/31 [==============================] - 3s 102ms/step - loss: 0.0049 - accuracy: 1.0000 - val_loss: 0.1371 - val_accuracy: 0.9712
Epoch 12/20
31/31 [==============================] - 3s 103ms/step - loss: 0.0043 - accuracy: 1.0000 - val_loss: 0.1226 - val_accuracy: 0.9808
Epoch 13/20
31/31 [==============================] - 3s 103ms/step - loss: 0.0032 - accuracy: 1.0000 - val_loss: 0.0864 - val_accuracy: 0.9712
Epoch 14/20
31/31 [==============================] - 3s 101ms/step - loss: 0.0057 - accuracy: 1.0000 - val_loss: 0.1484 - val_accuracy: 0.9808
Epoch 15/20
31/31 [==============================] - 3s 102ms/step - loss: 0.0142 - accuracy: 0.9979 - val_loss: 0.2122 - val_accuracy: 0.9615
Epoch 16/20
31/31 [==============================] - 3s 101ms/step - loss: 0.0997 - accuracy: 0.9733 - val_loss: 0.2564 - val_accuracy: 0.9327
Epoch 17/20
31/31 [==============================] - 3s 101ms/step - loss: 0.1513 - accuracy: 0.9497 - val_loss: 0.2443 - val_accuracy: 0.9038
Epoch 18/20
31/31 [==============================] - 5s 159ms/step - loss: 0.0875 - accuracy: 0.9774 - val_loss: 0.2463 - val_accuracy: 0.9423
Epoch 19/20
31/31 [==============================] - 5s 155ms/step - loss: 0.1616 - accuracy: 0.9466 - val_loss: 0.1779 - val_accuracy: 0.9519
Epoch 20/20
31/31 [==============================] - 3s 102ms/step - loss: 0.0611 - accuracy: 0.9836 - val_loss: 0.1074 - val_accuracy: 0.9808

#### Predictions

In [18]:
!pip install pydub

import os 
from multiprocessing import Pool

import pandas as pd
import numpy as np

from sklearn.metrics import f1_score
from scipy.sparse import lil_matrix

import tensorflow as tf 
from tqdm import tqdm

import librosa
from pydub import AudioSegment
from pydub.utils import make_chunks
from IPython.display import Audio

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pydub in /usr/local/lib/python3.8/dist-packages (0.25.1)

In [19]:
#assigning numerical class labels to each bird species

cls_label = {'Asiankoel' : 0, 'bluejay': 1, 'crow': 2, 'duck': 3, 'goaway': 4, 'lapwing': 5, 'owl': 6,
             'peafowl' : 7, 'sparrow':8, 'woodpeewe':9}

########################################################

def get_class_labels(r):
  x = r['class_name']
  label_names = x.split('_')

  label_nums=[]
  for l in label_names:
    indx = cls_label[l]
    label_nums.append(indx)

  return label_nums

In [20]:
# creating the dataframe which has path to wav file and it's label
# 2 species test dataset
label = []
path = []

root = '/content/drive/MyDrive/Bird/dataset/whole_dataset/mix_2'
for species in os.listdir(root):
    species_folder = root + '/' + species
    for audio in os.listdir(species_folder):
        audio_path = species_folder + '/' + audio
        path.append(audio_path)
        label.append(species)
        
df_mix_2 = pd.DataFrame({'path': path,
                         'class_name': label})

df_mix_2['class_label'] = df_mix_2.apply(get_class_labels, axis=1)

print(df_mix_2.shape)
df_mix_2.sample(5)

(334, 3)

,path,class_name,class_label
2,/content/drive/MyDrive/Bird/dataset/whole_data...,Asiankoel_goaway,"[0, 4]"
192,/content/drive/MyDrive/Bird/dataset/whole_data...,woodpeewe_sparrow,"[9, 8]"
277,/content/drive/MyDrive/Bird/dataset/whole_data...,sparrow_goaway,"[8, 4]"
108,/content/drive/MyDrive/Bird/dataset/whole_data...,duck_crow,"[3, 2]"
71,/content/drive/MyDrive/Bird/dataset/whole_data...,sparrow_bluejay,"[8, 1]"

In [21]:
# 3 species test dataset 
label = []
path = []

root = '/content/drive/MyDrive/Bird/dataset/whole_dataset/mix_3'
for species in os.listdir(root):
    species_folder = root + '/' + species
    for audio in os.listdir(species_folder):
        audio_path = species_folder + '/' + audio
        path.append(audio_path)
        label.append(species)
        
df_mix_3 = pd.DataFrame({'path': path,
                         'class_name': label})

df_mix_3['class_label'] = df_mix_3.apply(get_class_labels, axis=1)

print(df_mix_3.shape)
df_mix_3.sample(5)

(100, 3)

,path,class_name,class_label
41,/content/drive/MyDrive/Bird/dataset/whole_data...,duck_sparrow_bluejay,"[3, 8, 1]"
17,/content/drive/MyDrive/Bird/dataset/whole_data...,duck_owl_crow,"[3, 6, 2]"
36,/content/drive/MyDrive/Bird/dataset/whole_data...,goaway_sparrow_duck,"[4, 8, 3]"
4,/content/drive/MyDrive/Bird/dataset/whole_data...,duck_sparrow_goaway,"[3, 8, 4]"
42,/content/drive/MyDrive/Bird/dataset/whole_data...,duck_sparrow_bluejay,"[3, 8, 1]"

In [22]:
# whole test data i.e mixture of both 2 and 3 species audio files
df = pd.concat([df_mix_2, df_mix_3], ignore_index = True)
df.sample(5)

,path,class_name,class_label
205,/content/drive/MyDrive/Bird/dataset/whole_data...,woodpeewe_goaway,"[9, 4]"
154,/content/drive/MyDrive/Bird/dataset/whole_data...,lapwing_owl,"[5, 6]"
21,/content/drive/MyDrive/Bird/dataset/whole_data...,peafowl_bluejay,"[7, 1]"
206,/content/drive/MyDrive/Bird/dataset/whole_data...,woodpeewe_goaway,"[9, 4]"
386,/content/drive/MyDrive/Bird/dataset/whole_data...,crow_woodpeewe_goaway,"[2, 9, 4]"

In [23]:
# ref: https://www.kaggle.com/code/arailly/multi-label-f-beta-score/notebook

# metrics function

def label_to_sm(labels, n_classes):
    sm = lil_matrix((len(labels), n_classes))
    for i, label in enumerate(labels):
        sm[i, label] = 1  #eg: sm[0, [2,3]] = 1
    return sm

###############################################

def get_f1_score(y_true, y_pred):
  y_true_sm = label_to_sm(labels=y_true, n_classes=10)
  y_pred_sm = label_to_sm(labels=y_pred, n_classes=10)
  metric = f1_score(y_true=y_true_sm, y_pred=y_pred_sm, average='weighted')
  return metric

#################################################

def get_sm(y_true, y_pred):
  y_true_sm = label_to_sm(labels=y_true, n_classes=10)
  y_pred_sm = label_to_sm(labels=y_pred, n_classes=10)
  return y_true_sm, y_pred_sm

In [24]:
def get_split(path):
  myaudio = AudioSegment.from_file(path , "wav") 
  chunk_length_ms = 1500 # pydub calculates in millisec
  chunks = make_chunks(myaudio, chunk_length_ms) #Make chunks of one sec

  #Export all of the individual chunks as wav files
  paths =[]

  for i, chunk in enumerate(chunks):
      chunk_name = "chunk{0}.wav".format(i)
      paths.append(chunk_name)
      chunk.export(chunk_name, format="wav")

  return paths

##################################################

def get_mfcc(path):
    y, sr = librosa.load(path)
    S = librosa.feature.melspectrogram(y=y, sr=sr)
    mfccs = librosa.feature.mfcc(S=librosa.power_to_db(S), n_mfcc=40)
    mfccs = mfccs.T
    return np.resize(mfccs, (65, 40))

##################################################

def get_xqs(paths):
  xqs = []
  for i in range(6): #only using first 6 chunks
    t = get_mfcc(paths[i])
    xqs.append(t)
  return xqs

In [25]:
def get_probs(model, xqs):
  probs = []
  for xq in xqs:
    xq = xq.reshape((1,65,40))
    p = model.predict(xq, verbose = 0)
    probs.append(p)
  return np.array(probs)

def predict(model, xqs, num_species):
  probs = get_probs(model, xqs)
  # aggregrate
  # s = np.sum(probs, axis = 0)
  s = np.max(probs, axis = 0)
  if num_species == 2: 
    n = 2
  else:
    n = 3
  labels = np.argsort(s[0])[::-1][:n]
  return list(labels)

In [26]:
def test(model, df, num_species):
  y_true = list(df['class_label'])
  y_pred = []
  for i in tqdm(range(len(df))):
    path = df['path'][i]
    chunk_paths = get_split(path)
    xqs = get_xqs(chunk_paths)
    label = predict(model, xqs, num_species)
    y_pred.append(label)
  return y_true, y_pred

#########################################################

def evaluate(model, df_mix_2, df_mix_3):
  y_true_2, y_pred_2 = test(model, df_mix_2, 2)
  y_true_3, y_pred_3 = test(model, df_mix_3, 3)
  
  y_true = y_true_2 + y_true_3
  y_pred = y_pred_2 + y_pred_3
  score = get_f1_score(y_true, y_pred)
  
  return y_true, y_pred, score

In [29]:
y_true, y_pred, score = evaluate(model, df_mix_2, df_mix_3)
score

100%|██████████| 334/334 [08:25<00:00,  1.51s/it]
100%|██████████| 100/100 [02:27<00:00,  1.48s/it]

0.6465530252231135

In [30]:
from sklearn.metrics import classification_report

y_true, y_pred = get_sm(y_true, y_pred)
print(classification_report(y_true, y_pred))

              precision    recall  f1-score   support

           0       0.67      0.81      0.73        69
           1       0.52      0.33      0.40       101
           2       0.98      0.92      0.95       100
           3       0.76      0.75      0.75        88
           4       0.45      1.00      0.62       145
           5       0.97      0.79      0.87       136
           6       0.78      0.33      0.46        55
           7       0.46      0.81      0.59        63
           8       0.90      0.22      0.35       119
           9       0.96      0.50      0.66        92

   micro avg       0.66      0.66      0.66       968
   macro avg       0.74      0.65      0.64       968
weighted avg       0.75      0.66      0.65       968
 samples avg       0.67      0.67      0.67       968